### PR TITLE
Add EnemyDifficulty parameter to the BotConfig

### PR DESCRIPTION
**Pull request by vors**
Adding an option to specify some other than Easy opponent.

### CODE REVIEW

**Comment by alkurbatov** [comment]
Is it possible to use string constants like in the game (i.e. Veteran, Expert) instead of pure int?

**Comment by vors** [comment]
There is a difficulty enum, I don't see Veteran there :)
Sure we can parse strings, I personally think it will make it harder: you would need to lookup the correct way to spell it every time, or we would need a comment in the json around it, to allow easier copy-paste. So I have slight preference towards ints in this case.

```cpp
enum Difficulty {
    VeryEasy = 1,
    Easy = 2,
    Medium = 3,
    MediumHard = 4,
    Hard = 5,
    HardVeryHard = 6,
    VeryHard = 7,
    CheatVision = 8,
    CheatMoney = 9,
    CheatInsane = 10
};
```

**Comment by alkurbatov** [comment]
In Russian version of the game it is Veteran and so on :) 
One need to look at the api headers to copy-paste, while it is enough to specify the proper difficulty word. It seems that the bot is used by people who have difficulties with programming tasks so you will need some comment anyway :)

Std:map will simplify such string handling.

**Comment by davechurchill** [comment]
Thanks, I will add this

**Pull request merged**
