### PR TITLE
Better OS X building

### PR DESCRIPTION
**Pull request by alkurbatov**
* Add more compile time options.
* Include forgotten *.hpp files.
* Replace BOT_ASSERT with a dummy because of lack of DebugBrake() support.
* Fix several compiler warnings.

### CODE REVIEW

**Comment by alkurbatov** [comment]
As before please check Windows build.

Actually it would be nice to make some Travis support like I here:
https://github.com/virtuozzo/feathers-authentication-keystone/blob/master/.travis.yml
It allows to check compilation on each pull-request. However Travis could be tricky in this case because of sc2api and because we should check three platforms. Looks like a feature request to me.

Also the compiler reports a big number of unused variables. Dunno is it intended (e.g. it is placeholders for future functionality) or not so I didn't touch these.

**Comment by alkurbatov** [comment]
Please also pay attention that there should be some better alternative for debugBrake() in Linux/OS X case but that requires discussion.

**Comment by davechurchill** [comment]
Some of the requested changes conflict with changes I have made locally, so I will not accept this pull entirely right now. Could you suggest the osx build changes again once I have updated a little bit later this week?

Also, for this project I prefer to use size_t over unsigned

**Comment by alkurbatov** [comment]
No problem. Please push the new changes and I'll rebase this pull request.
Let it stay open.

>Also, for this project I prefer to use size_t over unsigned
No problem, lets make it size_t.

**Comment by alkurbatov** [comment]
Rebased to latest changes, use sc2::Tag instead of unsigned as it was suggested in #16.

**Comment by alkurbatov** [comment]
I found a nice hint for compilations warnings, see 0f10a37. Ugly -Wno-deprecated is not needed anymore.

**Comment by alkurbatov** [comment]
The conflicts resolved.

**Pull request merged**
