### PR TITLE
Generate Makefile for build under OS X

### PR DESCRIPTION
**Pull request by alkurbatov**
This pull request brings ability to generate a Makefile for OS X and Linux (not tested). The request includes the 'find' routine which tries to determine location of sc2api headers and libraries on the target system.

Unfortunately nobody has packaged sc2api yet so  we don't know how the package structure will be composed. Here we assume that:

a. Either /opt/local/include or /usr/local/include or /usr/include contains sc2api and sc2utils folders with proper headers inside.

b. The sc2api folder mentioned above contains the following folders inside:
* the proto/ folder with autogenerated starcraft2 protocol headers.
* the contrib/protobuf/src folder which contain Protobuf code (provided with sc2api package).

c. Either /opt/local/lib or /usr/local/lib or /usr/lib contains sc2api folder with all required libraries inside.

To build the project:
```bash
# Generate a Makefile
$ cmake .

# Build
$ make
```

### CODE REVIEW

**Comment by alkurbatov** [comment]
VS solutions could be generated in the same way if somebody improves the cmake's files. That will allow to eliminate the .vs folder completely and avoid manual edition of solutions files.

**Comment by davechurchill** [comment]
Thanks!

**Comment by vors** [comment]
@alkurbatov how can I get this `sc2api` folder from the (c) on macOS?
I build the https://github.com/Blizzard/s2client-api locally but the layout looks different.

**Comment by alkurbatov** [comment]
@vors if you build all the libs then you should place the libs into:
alkurbatov@Vika:~ $ ls /opt/local/lib/sc2api
libcivetweb.a       libprotobuf.a       libsc2api.a         libsc2protocol.a
libprotobuf-lite.a  libprotoc.a         libsc2lib.a         libsc2utils.a

Regarding headers structure and reasons behind it please refer to:
https://github.com/davechurchill/commandcenter/issues/21#issuecomment-323166029

**Comment by vors** [comment]
Cool, thank you for the explanation! I didn't work much with cmake and make before.
I tried to do a `make install` from s2client-api and hit this issue https://github.com/Blizzard/s2client-api/issues/90

I guess will copy libs manually to workaround it.

**Pull request merged**
