### PR TITLE
OS X compilation fixes

### PR DESCRIPTION
**Pull request by alkurbatov**
This pull request fix several small issues that breaks compilation under OS X.

### CODE REVIEW

**Comment by alkurbatov** [comment]
Hi! Thanks for the great work :)
Please pay attention that this pull-request wasn't tested under Windows so something could be broken.

Also it is not enough to build the project under OS X (I have more issues that were workarounded), probably I'll fix it in nearest future.

**Comment by davechurchill** [comment]
Looks good to me, will pull it and test it out

**Comment by davechurchill** [comment]
Did you make a Makefile? If so, feel free to pull request that as well

**Comment by alkurbatov** [comment]
I used cmake to generate Makefile in a way similar to sc2api so it can handle OS X and Linux builds. However some polishing is required, especially because I used hardcoded path to sc2api headers and libs.

**Pull request merged**
